### Список операций и предсказаний для userid 1 из Mongo
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnpO

### Список операций и предсказаний для userid 1 из Redis
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnpO

### Список операций и предсказаний, userid 2 из Mongo
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnp2

### Список операций и предсказаний, userid 2 из Redis
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnp2

### Список операций и предсказаний для userid 1 из Redis
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnpO

### Список операций и предсказаний, userid 2 из Redis
GET http://localhost:9999/payments?token=$2a$04$zWiNgAN9OXAX9iEFsqYXyuXxtXgEOn5qOIpw4x9Wnp6DJsTAOwnp2